global using System;
global using System.Net;
global using System.Data;
global using System.Linq;
global using System.Text;
global using System.Text.Json;
global using System.Reflection;
global using System.Diagnostics;
global using System.Collections;
global using System.Net.Security;
global using System.Globalization;
global using System.Buffers.Binary;
global using System.ComponentModel;
global using System.Linq.Expressions;
global using System.Text.Encodings.Web;
global using System.Collections.Generic;
global using System.Security.Cryptography;
global using System.Collections.Concurrent;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;

global using FluentValidation;
global using FluentValidation.Results;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Net.Http.Headers;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.Extensions.DependencyInjection;

global using Utilities.Core.Shared.Utils;
global using Utilities.Core.Shared.Services;
global using Utilities.Core.Shared.Settings;
global using Utilities.Core.Shared.Extensions;
global using Utilities.Core.Shared.Exceptions;
global using Utilities.Core.Shared.Converters;

global using MainConstantsCore = Utilities.Core.Shared.Constants.MainConstants;
global using RegexConstantsCore = Utilities.Core.Shared.Constants.RegexConstants;
global using FormatConstantsCore = Utilities.Core.Shared.Constants.FormatConstants;
global using MessageConstantsCore = Utilities.Core.Shared.Constants.MessageConstants;
global using EnvironmentConstantsCore = Utilities.Core.Shared.Constants.EnvironmentConstants;
global using HttpStatusCodeConstantsCore = Utilities.Core.Shared.Constants.HttpStatusCodeConstants;
