namespace Hogar.Core.Shared.Constants;

public static class HttpStatusCodeConstants
{
    public const ushort CFG_BAD_REQUEST = 400;
    public const ushort CFG_UNAUTHORIZED = 401;
    public const ushort CFG_PAYMENT_REQUIRED = 402;
    public const ushort CFG_FORBIDDEN = 403;
    public const ushort CFG_NOT_FOUND = 404;
    public const ushort CFG_METHOD_NOT_ALLOWED = 405;
    public const ushort CFG_NOT_ACCEPTABLE = 406;
    public const ushort CFG_PROXY_AUTHENTICATION_REQUIRED = 407;
    public const ushort CFG_REQUEST_TIMEOUT = 408;
    public const ushort CFG_CONFLICT = 409;
    public const ushort CFG_GONE = 410;
    public const ushort CFG_LENGTH_REQUIRED = 411;
    public const ushort CFG_PRECONDITION_FAILED = 412;
    public const ushort CFG_REQUEST_ENTITY_TOO_LARGE = 413;
    public const ushort CFG_REQUEST_URI_TOO_LONG = 414;
    public const ushort CFG_UNSUPPORTED_MEDIA_TYPE = 415;
    public const ushort CFG_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    public const ushort CFG_EXPECTATION_FAILED = 417;
    public const ushort CFG_IM_A_TEAPOT = 418;
    public const ushort CFG_METHOD_FAILURE = 420;
    public const ushort CFG_UNPROCESSABLE_ENTITY = 422;
    public const ushort CFG_LOCKED = 423;
    public const ushort CFG_FAILED_DEPENDENCY = 424;
    public const ushort CFG_TOO_EARLY = 425;
    public const ushort CFG_UPGRADE_REQUIRED = 426;
    public const ushort CFG_PRECONDITION_REQUIRED = 428;
    public const ushort CFG_TOO_MANY_REQUESTS = 429;
    public const ushort CFG_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    public const ushort CFG_NO_RESPONSE_NGINX = 444;
    public const ushort CFG_RETRY_WITH_IIS = 449;
    public const ushort CFG_BLOCKED_BY_WP_CTRLS = 450;
    public const ushort CFG_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    public const ushort CFG_CLIENT_CLOSED_REQUEST_NGINX = 499;
    public const ushort CFG_INTERNAL_SERVER_ERROR = 500;
    public const ushort CFG_NOT_IMPLEMENTED = 501;
    public const ushort CFG_BAD_GATEWAY = 502;
    public const ushort CFG_SERVICE_UNAVAILABLE = 503;
    public const ushort CFG_GATEWAY_TIMEOUT = 504;
    public const ushort CFG_HTTP_VERSION_NOT_SUPPORTED = 505;
    public const ushort CFG_VARIANT_ALSO_NEGOTIATES = 506;
    public const ushort CFG_INSUFFICIENT_STORAGE = 507;
    public const ushort CFG_LOOP_DETECTED = 508;
    public const ushort CFG_BANDWIDTH_LIMIT_EXCEEDED = 509;
    public const ushort CFG_NOT_EXTENDED = 510;
    public const ushort CFG_NETWORK_AUTHENTICATION_REQUIRED = 511;
}
